### ISSUE TITLE
在主程序 main.py 中关于退出的建议

### ISSUE THREAD

**Issue by hi-zcy** [LC044/TraceBoard#1]
可以使用 sys.exit(0) 吗？

**Comment by LC044** [comment]
不知道为什么，使用sys.exit(0) 无法直接退出

**Comment by hi-zcy** [comment]
我知道了，os._exit()是线程级别的，但sys.exit()是模块级别的。参见官方文档：
```
os._exit()
```
![image](https://github.com/user-attachments/assets/41bf848a-cb61-4c6a-a85a-5c037c92adaa)
```
sys.exit()
```
![image](https://github.com/user-attachments/assets/51b75e75-ac84-46e9-b429-bbcd0e67533c)

**Comment by LC044** [comment]
明白了
